package com.sample.app;

import java.util.Date;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.sample.model.System;
import com.sample.dao.SystemRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private SystemRepository systemRepository;
	final static Logger logger=Logger.getLogger(MainController.class); 
	@GetMapping(path="/add") // Map ONLY GET Requests
        public @ResponseBody String addNewUser (@RequestParam(value="fname",required=false) String fname,@RequestParam(value="lname",required=false) String lname,@RequestParam(value="age",required=false) String age) {
                // @ResponseBody means the returned String is the response, not a view name
                // @RequestParam means it is a parameter from the GET or POST request

                System n = new System();

                n.setlName(lname);

                n.setfName(fname);

                n.setAge(age);

                systemRepository.save(n);
              //  System.out.println("Hello World all",name);
                logger.info("Inside add request ");
                return "Saved received the name "+fname+" "+lname+" "+age;
        }

	@GetMapping(path="/all")
	public @ResponseBody Iterable<System> getAllUsers() {
		// This returns a JSON or XML with the users
		return systemRepository.findAll();
	}
}
